{
	"error.pyrite.region.random_point_unsupported": "Cannot generate a random point in a region of type '%s'"
}